# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.6.0"
Vagrant.configure("2") do |config|
 
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", path:"scripts/install.sh"
  config.vm.provider "virtualbox" do |v|
     v.memory = 4096
     v.cpus = 2
     end 
end
